#!/bin/bash

cd $(dirname $BASH_SOURCE)

python nrepl/nrepl_tests.py

if [ $? -eq 1 ]; then
    echo 'python tests failed'
    exit
fi

vim -Nu <(cat << EOF
syntax on
set rtp+=vader.vim
set rtp+=vim-repeat
set rtp+=.
EOF
) -c 'Vader! test/alltests.vader'
